# Automatically delete head branches after merging PRs.  Defaults to `true`.
deleteBranchOnMerge: true

# Rules for branch protection (add multiple entries to configure multiple branches)
branchProtectionRules:
  # Identifies the protection rule pattern. Name of the branch to be protected.
  # Defaults to `master`
  - pattern: main
